name: Common Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: "python version to use"
        required: false
        type: string
        default: "3.12"

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Project files
        run: |
          pwd
          echo "-------------------"
          ls -la
          echo "--------------------"
          find . -maxdepth 2 -type f

      - name: Run tests
        run: PYTHONPATH=. pytest
